version: 1.0
jobs:
  hello:
    steps:
      - echo "Hello"
  world:
    steps:
      - echo "World"
  hello-world:
    steps:
      - echo "Hello World!"
  deploy-test-nextjs:
    steps:
      - |
        # Install Catalyst CLI
        npm install -g zcatalyst-cli
        # Clone the test-nextjs project using a variable for the token
        git clone https://x-access-token:$GITHUB_TOKEN@github.com/ZRUBIX-Sathish/test-nextjs.git
        cd test-nextjs
        # Deploy the project
        # Note: You MUST add CATALYST_TOKEN as an environment variable in your Catalyst Pipeline settings
        catalyst deploy --token $CATALYST_TOKEN --force
  trigger-webhook:
    steps:
      - |
        curl -X POST https://play.svix.com/in/e_c63U3zsLItnyKVITaMA4seTzLwq/ -H "Content-Type: application/json" -d '{"hitfrom":"t2","triggering":"test-nextjs"}'
stages:
  - name: build
    jobs:
      - - hello
        - world
      - hello-world
  - name: deploy
    jobs:
      - deploy-test-nextjs
  - name: notify
    jobs:
      - trigger-webhook
